#!/usr/bin/env python3
from __future__ import annotations
import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "BG3_WIKI_HD_ASSET_REPORT.json"
OUT_JS = ROOT / "assets/js/data/hd-asset-manifest.js"
OUT_REPORT = ROOT / "IMAGE_FAST_PATH_REPORT.json"
PREFERENCE = [".webp", ".png", ".jpg", ".jpeg"]

def choose(folder: Path, key: str):
    existing = [folder / f"{key}{ext}" for ext in PREFERENCE if (folder / f"{key}{ext}").is_file()]
    return existing[0] if existing else None, existing

def rel_web(path: Path) -> str:
    return "./" + path.relative_to(ROOT).as_posix()

def main():
    if not REPORT.exists():
        raise SystemExit("Missing BG3_WIKI_HD_ASSET_REPORT.json")
    report = json.loads(REPORT.read_text(encoding="utf-8"))
    items = report.get("items", [])
    targets = {"spell": [], "equipment": []}
    for row in items:
        kind, key = row.get("type"), row.get("key")
        if kind in targets and key and key not in targets[kind]:
            targets[kind].append(key)

    maps = {"spell": {}, "equipment": {}}
    ext_counts = {"spell": Counter(), "equipment": Counter()}
    missing = []
    multi = []
    selected_bytes = 0
    target_raw_bytes = 0
    avoided_probes = 0

    for kind, keys in targets.items():
        folder = ROOT / "assets/hd" / ("spells" if kind == "spell" else "equipment")
        for key in sorted(keys):
            selected, variants = choose(folder, key)
            if not selected:
                missing.append(f"{kind}:{key}")
                continue
            maps[kind][key] = rel_web(selected)
            ext_counts[kind][selected.suffix.lower()] += 1
            selected_bytes += selected.stat().st_size
            target_raw_bytes += sum(p.stat().st_size for p in variants)
            if len(variants) > 1:
                multi.append({
                    "type": kind,
                    "key": key,
                    "selected": rel_web(selected),
                    "variants": [rel_web(p) for p in variants],
                })
            # Old local probe order was webp -> png -> jpg.
            # Count failed local probes avoided before the first real file.
            old_order = [".webp", ".png", ".jpg"]
            if selected.suffix.lower() in old_order:
                avoided_probes += old_order.index(selected.suffix.lower())

    if missing:
        raise SystemExit("Missing HD target assets: " + ", ".join(missing))

    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    js = (
        "/* Generated by tools/generate-hd-asset-manifest.py. */\n"
        "export const spellHdAssets=Object.freeze("
        + json.dumps(maps["spell"], ensure_ascii=False, separators=(",", ":"))
        + ");\n"
        "export const equipmentHdAssets=Object.freeze("
        + json.dumps(maps["equipment"], ensure_ascii=False, separators=(",", ":"))
        + ");\n"
        "export const hdAssetManifestMeta=Object.freeze({spell:"
        + str(len(maps["spell"]))
        + ",equipment:"
        + str(len(maps["equipment"]))
        + ",total:"
        + str(len(maps["spell"]) + len(maps["equipment"]))
        + "});\n"
    )
    OUT_JS.write_text(js, encoding="utf-8")

    all_hd_files = [
        p for p in (ROOT/"assets/hd").rglob("*")
        if p.is_file() and p.suffix.lower() in PREFERENCE
    ]
    raw_hd_bytes = sum(p.stat().st_size for p in all_hd_files)

    perf = {
        "version": "V8.2.5 asset fast path",
        "target_keys": {
            "spell": len(maps["spell"]),
            "equipment": len(maps["equipment"]),
            "total": len(maps["spell"]) + len(maps["equipment"]),
        },
        "selected_extension_counts": {
            k: dict(v) for k, v in ext_counts.items()
        },
        "raw_hd_files": len(all_hd_files),
        "raw_hd_bytes": raw_hd_bytes,
        "selected_primary_bytes": selected_bytes,
        "extra_variant_bytes_in_repo": max(0, target_raw_bytes - selected_bytes),
        "keys_with_multiple_variants": len(multi),
        "estimated_avoided_local_probe_requests_per_full_catalog_walk": avoided_probes,
        "before": {
            "strategy": "placeholder + IntersectionObserver + guessed .webp/.png/.jpg probes + remote fallbacks",
            "final_spell_images_forced_eager": True,
        },
        "after": {
            "strategy": "generated exact local manifest + direct native lazy src; JS only activates on local error",
            "final_spell_images_forced_eager": False,
            "remote_fallbacks_requested_on_success": 0,
        },
        "multiple_variants": multi,
        "next_optional_step": "If real network waterfall is still heavy, generate ~192px WebP thumbnails and use srcset; do not do this until measured.",
    }
    OUT_REPORT.write_text(json.dumps(perf, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(json.dumps({
        "spell": len(maps["spell"]),
        "equipment": len(maps["equipment"]),
        "total": len(maps["spell"]) + len(maps["equipment"]),
        "avoided_local_probe_requests_estimate": avoided_probes,
        "selected_primary_mb": round(selected_bytes/1024/1024, 2),
        "raw_hd_mb": round(raw_hd_bytes/1024/1024, 2),
        "manifest": str(OUT_JS),
        "report": str(OUT_REPORT),
    }, ensure_ascii=False, indent=2))

if __name__ == "__main__":
    main()
